src/js/AuditRule.js
src/js/externs/externs.js
test/index.html
test/js/audit-rule-test.js

Fixes #126
@RickSBrown PTAL
I thought I might be able to submit a PR to your PR, but it turns out you can only send PRs to the repo you forked from. Seems to miss the point of git a bit! Anyway, your original change is in there.

Use getDistributedNodes to get nodes distributed into shadowRoots

---

src/audits/AriaOnReservedElement.js
src/audits/AriaOwnsDescendant.js
src/audits/AriaRoleNotScoped.js
src/audits/AudioWithoutControls.js
src/audits/BadAriaAttribute.js
src/audits/BadAriaAttributeValue.js
src/audits/BadAriaRole.js
src/audits/ControlsWithoutLabel.js
src/audits/DuplicateId.js
src/audits/FocusableElementNotVisibleAndNotAriaHidden.js
src/audits/HumanLangMissing.js
src/audits/ImageWithoutAltText.js
src/audits/LinkWithUnclearPurpose.js
src/audits/LowContrast.js
src/audits/MainRoleOnInappropriateElement.js
src/audits/MeaningfulBackgroundImage.js
src/audits/MultipleAriaOwners.js
src/audits/NonExistentAriaRelatedElement.js
src/audits/PageWithoutTitle.js
src/audits/RequiredAriaAttributeMissing.js
src/audits/RequiredOwnedAriaRoleMissing.js
src/audits/TabIndexGreaterThanZero.js
src/audits/UnfocusableElementsWithOnClick.js
src/audits/UnsupportedAriaAttribute.js
src/audits/VideoWithoutCaptions.js

Hello, I recently updated the [Audit Rules](https://github.com/GoogleChrome/accessibility-developer-tools/wiki/Audit-Rules) wiki page to simplify the anchors on every rule, so they are easier to link from other projects ([see an example](https://github.com/accesslint/access_lint)).
I think that using just the audit rule ID, for example `#ax_aria_12` is much clearer than using a longer English string like `#-ax_aria_12--this-element-does-not-support-aria-roles-states-and-properties`.
The description text, "this element does not support aria roles states and properties" is much more prone to change in the future than the ID "ax_aria_12". Also, the anchors included a whitespace at the beginning that made them look a bit weird.
This PR changes the links to every audit rule to use the new …

updates links to Audit Rules wiki to use the new anchors

---

README.md

Wrote code example on how to run the audit javascript via Selenium WebDriver JavascriptExecutor.
+ Some bits about caching for common sense.

+ Selenium WebDriver example (scala)

---

.gitignore
Changelog.md
Gruntfile.js
package.json
src/util/gh_repo.coffee

This PR provides tooling for automating a lot of the `grunt` work involved in shipping out new releases.
Along with some general cleanups and enhancements (see below), the major change is the introduction of the `grunt release` task, which will perform the following tasks:
* Prompt the operator for release information (git remote, github repo info, etc...).
* Create a new build.
* Run the full suite of unit tests (currently against the source, but I'd like to make tests run against compiled bundle in the future).
* Copy the build into `dist/`.
* Bump `version` field in `package.json` and `bower.json`.
* Extract release notes from the changelog (everything above the last release header).
* Add the new release header to the changelog.
* Commit and push `package.json`, `bower.json`, `dist`. …

Release automation

---

Gruntfile.js

* Add `—dry-run` option support for the `changelog` and `gh-release` tasks.
* Skip the bundle compilation, unit testing and bundle distribution tasks when `—dry-run` is specified.

Enhance dry-run release tasks

---

bower.json
package.json

* Both NPM and Bower specify that the `license` field should be a valid
SPDX license ID.
* https://github.com/bower/bower.json-spec#license
* https://docs.npmjs.com/files/package.json#license

Use SPDX License IDs

---

src/js/BrowserUtils.js

Formerly known as matchesSelector(), with many vendor prefixes as seen in this function.
I'm using ADT in a jsdom environment, which doesn't support any vendor-prefixed variations
of this function.
http://caniuse.com/#feat=matchesselector

Add .matches() as default choice for browserUtils.matchSelector

---

Changelog.md
bower.json
dist/js/axs_testing.js
scripts/output_wrapper.txt

* Wrap the output into an AMD compatible module if possible. Otherwise, keep exporting `axs` and `goog` into the global scope.
* Fresh rebuild of `axs_testing.js` bundle.
* Update `bower.json` config to advertise support for AMD module.

Export AMD module

---

Changelog.md
src/audits/FocusableElementNotVisibleAndNotAriaHidden.js

Actually this is a workaround, not a fix because the bug is in closure compiler. I'll break it down in detail below.
First understand that the function `axs.properties.findTextAlternatives` can legitimately return `null`.
Then take a look at the way we call it:
```
var textAlternatives = axs.properties.findTextAlternatives(element, {});
if (!textAlternatives || textAlternatives.trim() === '')
```
All good. But then take a look at what closure compiler produces:
```
return "" === axs.properties.findTextAlternatives(a, {}).trim() ? !1 : !0;
```
That will throw an exception if the return value is null.
The easiest workaround is to get closure compiler to produce something else. The proposed change does not change the logic of the audit but results in safe code generated by closure compiler: …

Fixes issue #183

---

README.md
src/js/Audit.js
test/js/audit-configuration-test.js

* Overwrite `AuditConfiguration` properties defined in the constructor with properties found in payload parameter.
* Add test for new behaviour.
* Add usage example in docs.
* Fixes #164

Add support for config payload for AuditConfiguration

---

Changelog.md
src/js/Color.js
test/js/color-test.js

Fixes issue #180 
This bug is responsible for the only failing unit test (`LowContrast - "Opacity is handled"`) in:
* Firefox
* IE11
* MS Edge
This fix makes 100% of unit tests pass in those browsers.
Also checked Chrome, Opera and Safari, all 100%.

Add a special case to handle color `"transparent"` to fix #180.

---

Changelog.md
src/js/AccessibilityUtils.js
test/audits/bad-aria-attribute-value-test.js

Looks like the intent was for `decimal` and `number` to be validated the same way instead of `decimal` and `integer`.

Fixes issue #182 and adds a unit test to check this condition.

---

Changelog.md
src/js/Constants.js
test/audits/aria-role-not-scoped-test.js

Closes #204 
The required context role for `tab` ended up on `tablist` instead.
This motivates me to get onto #105

Fix ARIA tablist and ARIA tab scope

---

Changelog.md
src/audits/LinkWithUnclearPurpose.js
test/audits/link-with-unclear-purpose.js

This PR allows links to be labelled by their textcontent (as before) and additionally:
* aria-label
* aria-labelledby
* img with alt text
There is no way for us to truly validate the the link is *visually* meaningful since it would be really hard to analyse what the image looks like - this really only confirms that the link is meaningful to AT.
@alice PTAL

Link with unclear purpose audit handles img with alt and aria-label

---

scripts/output_wrapper.txt

This restores previous behavior that allowed access to `axs.utils`
We are using [a11y](https://github.com/addyosmani/a11y), which reformats the report for the CLI. They are using `axs.utils.getQuerySelectorText` to get a helpful description of the element which fails the audit ([see code here](https://github.com/addyosmani/a11y/blob/master/audits.js#L68)). When the AMD pattern was implemented, the fallback did not maintain previous behavior of exporting all of `axs`. This breaks output when using a11y.
The Pivotal UI Team
@atomanyih @ctaymor @gpleiss @kennyw12 @matt-royal @nicw @stubbornella

Export all of axs when not using AMD

---

Changelog.md
src/js/Constants.js
test/audits/unsupported-aria-attribute-test.js

Fixed the reported bug and found another related one we had not encountered yet - input with no `type` is a text input.
Actually an input of any unknown type is a text input - we probably don't handle that, that should probably be a separate issue..? For example `<input type="foo"/>` I'm thinking that's an outlier and no point holding up this fix for it.
Also completely ignoring the fact that `aria-required` should not be used when an exactly equivalent native attribute is available - that should be a different audit anyway because SEVERE is a bit extreme in that case.

Fixes issue #225

---

src/audits/LinkWithUnclearPurpose.js
test/audits/link-with-unclear-purpose.js

Links which were hidden were failing the LinkWithUnclearPurpose audit, because they were being audited, but findTextAlternatives wasn't returning their text.
The Pivotal UI Team
@atomanyih @ctaymor @d-reinhold @kennyw12 @matt-royal @nicw @stubbornella

Hidden links no longer fail meaningful link audit

---

Changelog.md
src/js/AuditRule.js
test/js/audit-rule-test.js

Revert #150

---

Changelog.md
src/js/Properties.js
test/js/properties-test.js

This is kind of scary because `findTextAlternatives` is a big and complex routine and I'm worried that the proposed change might have implications I have not considered.
That said, it passes all existing and new unit tests which gives me enough confidence to say @alice PTAL.

Fixes issue #217 findTextAlternatives not ignoring hidden elements

---

Changelog.md
src/audits/AriaRoleNotScoped.js
src/audits/DuplicateId.js
src/audits/MultipleAriaOwners.js
src/audits/RoleTooltipRequiresDescribedBy.js
src/js/AccessibilityUtils.js
test/audits/duplicate-id-test.js
test/js/utils-test.js

Implements the decision in #141 
@alice PTAL

Closes issue #141 - only audit IDs in IDREFs

---

README.md

Given the huge number of downloads we should probably advertise this.
[Can see it working here](https://github.com/ricksbrown/accessibility-developer-tools/tree/3111851afd57db7d435b8b44735d5942fd51063b).

Added some shiny badges

---

tools/runner/audit.js

In the case that the audited website has an exposed AMD loader, the auditor fails, because `window.axs` is undefined. This PR fixes this.

fix: make phantom audit work with websites that expose an AMD loader

---

src/js/AccessibilityUtils.js
test/js/utils-test.js

Currently when the CSS selector is generated for an ID that contains special characters (let's say dots) these are not escaped, resulting in an incorrect query selector.
Example `<div id="id.with.dots">` should yield `#id\.with\.dots`. Instead it yields `#id.with.dots` which searches for an element with the ID `id` and two classes `with` and `dots`.
This PR fixes this and adds a test.

fix: escape special characters to be used in a query selector string

---

.gitmodules

Hi there,
When trying to do a recursive clone I ran into this message:
```
Cloning into 'lib/closure-library'...
fatal: repository 'https://code.google.com/p/closure-library/' not found
Clone of 'https://code.google.com/p/closure-library/' into submodule path 'lib/closure-library' failed
```
So I just updated the submodule to point to the new repo on Google with the latest sha.

Update submodule to use latest closure-library on GitHub

---

Gruntfile.js
main.js
package.json

First, thanks for a wonderful library! I'm using it to automatically test our website (https://openstax.org) and was not happy with shoehorning [squizlabs/HTML_CodeSniffer](https://github.com/squizlabs/HTML_CodeSniffer) to run automatically.
The first commit just changes `package.json` to expose the `dist/js/axs_testing.js` file for node users which is the bulk of getting it to work.
The second commit unwraps the `axs` package to expose the `Audit*` objects directly so you can write something like:
```js
var axs = require('accessibility-developer-tools');
axs.Audit.run();
```
If you would prefer just the 1st commit I can happily revert the second commit or change anything else 😄 . Thanks again!

Make the npm module requireable

---

src/js/AccessibilityUtils.js
test/audits/role-tooltip-requires-described-by-test.js

In the case of an element referred to via its ID in an `aria-describedby` and that element not existing, the function `axs.utils.getAriaIdReferrers` returns `null` which is expected by `RoleTooltipRequiresDescribedBy` to always return a `NodeList`.
This then fails with
```
TypeError: 'null' is not an object (evaluating 'axs.utils.getAriaIdReferrers(a, \"aria-describedby\").length')
```
This PR fixes this and adds a test for it.

fix: null access for missing referrers of aria-describedby

---

src/js/DOMUtils.js
src/js/externs/externs.js
test/js/composed-parent-node-test.js

This PR updates `axs.dom.composedParentNode` to use `assignedSlot` (new in Shadow DOM v1, [link](https://github.com/w3c/webcomponents/commit/224f6b8e1e48f5db0a592ec8fb5162770062be24)) if available and doesn't attempt to call `getDestinationInsertionPoints` (removed) if it isn't available.
Some of the tests specifically check the behavior of content elements with a set `select` attribute; I changed these to use slots with `name` attributes and added `slot` attributes to the relevant nodes outside the shadow tree to get the same 'distributed vs. not distributed' behavior. It might be worth renaming the tests since they're not about content elements anymore.
(fixes #312)

Update `composedParentNode` for Shadow DOM v1.

---

src/js/DOMUtils.js
test/js/utils-test.js

Some browser supported don't support Shadow DOM. However the DOMUtils expect this. Fixes #255.

fix: don't die in browsers that do not support shadow DOM. Fixes #255.

---

src/js/Properties.js
test/js/properties-test.js

handle nodes hosted in a <template>
