test/audits/link-with-unclear-purpose.js

Add link-with-unclear-purpose.js

---

src/audits/AriaOnReservedElement.js
src/audits/AriaOwnsDescendant.js
src/audits/AriaRoleNotScoped.js
src/audits/AudioWithoutControls.js
src/audits/BadAriaAttribute.js
src/audits/BadAriaAttributeValue.js
src/audits/BadAriaRole.js
src/audits/ControlsWithoutLabel.js
src/audits/DuplicateId.js
src/audits/FocusableElementNotVisibleAndNotAriaHidden.js
src/audits/HumanLangMissing.js
src/audits/ImageWithoutAltText.js
src/audits/LinkWithUnclearPurpose.js
src/audits/LowContrast.js
src/audits/MainRoleOnInappropriateElement.js
src/audits/MeaningfulBackgroundImage.js
src/audits/MultipleAriaOwners.js
src/audits/NonExistentAriaRelatedElement.js
src/audits/PageWithoutTitle.js
src/audits/RequiredAriaAttributeMissing.js
src/audits/RequiredOwnedAriaRoleMissing.js
src/audits/TabIndexGreaterThanZero.js
src/audits/UnfocusableElementsWithOnClick.js
src/audits/UnsupportedAriaAttribute.js
src/audits/VideoWithoutCaptions.js
src/js/AccessibilityUtils.js
src/js/Properties.js

Added all blank wiki URLs.
Cleaned up `goog.require` import statements.

Added all blank wiki URLs.

---

src/js/externs/externs.js

Remove extraneous externs

---

Gruntfile.js

@ckundo PTAL (Not sure how we missed this this whole time...)
Ref #144

Remove extraneous quotes from output_wrapper param

---

src/audits/AriaRoleNotScoped.js
src/audits/RequiredOwnedAriaRoleMissing.js
src/js/AccessibilityUtils.js
test/js/utils-test.js

Updates to axs.utils.getRoles and related changes to some Audits.

---

dist/js/axs_testing.js
package.json

@alice thought I would get the ball rolling from our last call by cutting a new release :) If you're happy with these changes, I'm happy to take care of the tagging/publishing part this time and you can take that on for the next one.
Updates:
* Verified all tests are passing
* Bumped development dependencies
* Compiled new build for check-in (current checkin is ~1 year old)
* Bumped version to 2.7.0.

New release

---

src/audits/ImageWithoutAltText.js
src/js/Properties.js
test/audits/image-without-alt-text-test.js
test/index.html
test/js/properties-test.js

Fixes #154
@ckundo or @RickSBrown PTAL

Check for any text alternatives when assessing unlabeled images

---

bower.json

* Once this is merged, the module can be registered into the bower registry.
* Fixes #157

Add bower config

---

Gruntfile.js

Don't clean dist/ unless copying to dist

---

src/audits/FocusableElementNotVisibleAndNotAriaHidden.js
test/audits/focusable-element-not-visible-not-aria-hidden-test-browser.js
test/gui-browser.html
test/index.html

Fix hidden case for FocusableElementNotVisibleNotAriaHidden

---

Changelog.md
src/audits/MultipleLabelableElementsPerLabel.js
src/js/AccessibilityUtils.js
test/audits/multiple-labelable-elements-per-label-test.js
test/index.html

Fail if a `<label>` contains more than one labelable item.

---

Changelog.md

Just to follow up from #189 - here's the corresponding Changelog entry.

Added changes from #189 to changelog

---

.travis.yml

* See: http://docs.travis-ci.com/user/migrating-from-legacy

Migrate to Travis' container infrastructure

---

Changelog.md
src/audits/ControlsWithoutLabel.js
test/audits/controls-without-label-test.js

Closes #202 
Pretty straightforward fix (I hope).
Spent much more time on unit tests than on the fix.
@alice PTAL

Fix issue #202 - an HTML Button containing an img with alt text should pass ControlsWithoutLabel

---

Changelog.md
src/audits/LowContrast.js
src/js/AccessibilityUtils.js
src/js/Constants.js
test/audits/low-contrast-test.js
test/js/utils-test.js

Disabled elements should be ignored by low contrast audit

---

README.md

typo on README.

---

Changelog.md
src/audits/UncontrolledTabpanel.js
test/audits/uncontrolled-tabpanel-test.js
test/index.html

per the recomendations from the WAI-ARIA guidelines on the role tabpanel
found here: http://www.w3.org/TR/wai-aria/roles#tabpanel
Addresses #228

New rule: tabpanel should be related to a tab

---

Changelog.md
Gruntfile.js
src/audits/AriaRoleNotScoped.js
src/audits/ControlsWithoutLabel.js
src/audits/FocusableElementNotVisibleAndNotAriaHidden.js
src/js/AccessibilityUtils.js
src/js/AuditRule.js
src/js/DOMUtils.js
src/js/Properties.js
test/audits/focusable-element-not-visible-not-aria-hidden-test-browser.js
test/audits/focusable-element-not-visible-not-aria-hidden-test.js
test/audits/link-with-unclear-purpose.js
test/gui-browser.html
test/index.html
test/js/audit-rule-test.js
test/js/composed-parent-node-test.js

Including composedParentNode a method to get the composed tree parent for a node.
Fixes #171.

Add DOMUtils.js.

---

Changelog.md
src/js/AccessibilityUtils.js

Don't need to take container scroll into account if container is body

---

src/js/AuditRule.js
src/js/DOMUtils.js
test/audits/aria-on-reserved-element-test.js
test/audits/aria-owns-descendant-test.js
test/audits/multiple-aria-owners-test.js
test/audits/non-existent-aria-related-element-test.js
test/js/audit-rule-test.js

Based on #233 but with new logic based on the changes in #242.
Includes @kennyw12's original change.

Ignore selectors fix

---

test/audits/role-tooltip-requires-described-by-test.js

Addresses issue #301

---

.travis.yml
Gruntfile.js
package.json

Use google-closure-compiler node module and bring closure-compiler library up to date
